PasteBinClone/PasteBinClone.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using PasteBinClone.Web.Interfaces;
using PasteBinClone.Web.Models;
using PasteBinClone.Web.Models.ViewModel;
using PasteBinClone.Web.Request;
using System.Text.Json.Serialization;

namespace PasteBinClone.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly IBaseService _categoryService;
        private readonly IDistributedCache _cache;

        public CategoryController(IBaseService categoryService, IDistributedCache cache)
        {
            _categoryService = categoryService;
            _cache = cache;
        }

        public async Task<IActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.GetAll(RouteConst.CategoryRoute,
                accessToken);

            if(response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a list of Categories
                List<CategoryVM> categories = JsonConvert.DeserializeObject<List<CategoryVM>>(response.Data.ToString());

                return View(categories);
            }
            else
            {
                return NotFound();
            }
        }

        //Get-Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Post-Create
        [HttpPost]
        public async Task<IActionResult> Create(CategoryVM categoryVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.Post(categoryVM, 
                RouteConst.CategoryRoute,accessToken);

            if(response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        //Get-Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.GetById(id, 
                RouteConst.CategoryRoute, accessToken);

            if(response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a Category
                CategoryVM categories = JsonConvert.DeserializeObject<CategoryVM>(response.Data.ToString());

                return View(categories);
            }
            else
            {
                return NotFound();
            }

        }

        //Post-Edit
        [HttpPost]
        public async Task<IActionResult> Edit(CategoryVM categoryVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.Put(categoryVM, 
                RouteConst.CategoryRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        //Get-Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.GetById(id, 
                RouteConst.CategoryRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a Category
                CategoryVM categories = JsonConvert.DeserializeObject<CategoryVM>(response.Data.ToString());

                return View(categories);
            }
            else
            {
                return NotFound();
            }
        }

        //Post-Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _categoryService.Delete(id, 
                RouteConst.CategoryRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                _cache.Remove("filters");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

PasteBinClone/PasteBinClone.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PasteBinClone.Web.Interfaces;
using PasteBinClone.Web.Models.ViewModel;
using PasteBinClone.Web.Request;
using System.Linq;

namespace PasteBinClone.Web.Controllers
{
    [Authorize]
    public class CommentController(IBaseService baseService, IUserInfo userInfo) : Controller
    {
        private readonly IBaseService _baseService = baseService;
        private readonly IUserInfo _userInfo = userInfo;

        [HttpPost]
        public async Task<IActionResult> Create(CommentVM comment)
        {
            string returnUrl = Request.Headers["Referer"].ToString();

            var accessToken = await HttpContext.GetTokenAsync("access_token");

            comment.UserId = _userInfo.GetUserId(accessToken);

            await _baseService.Post(comment, RouteConst.CommentRoute, accessToken);

            return Redirect(returnUrl);
        }

        [HttpGet]
        public async Task<IActionResult> Comments(string pasteId, int pageNumber = 1)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetById(pasteId, RouteConst.CommentRoute, accessToken, obj: pageNumber);

            if (response != null && response.IsSuccess)
            {
                
                CommentsResponse commentsResponse = JsonConvert.DeserializeObject<CommentsResponse>(response.Data.ToString());

                GetCommentsVM comments = new GetCommentsVM
                {
                    Comments = commentsResponse.CommentVMs,
                    ReturnUrl = "https://localhost:44306/Paste/Details/" + pasteId,
                    PageNumber = pageNumber,
                    PasteId = pasteId,
                    IsActiveRightArrow = commentsResponse.TotalPages > pageNumber ? true : false,
                    IsActiveLeftArrow = pageNumber > 1 ? true : false      
                };

                return View(comments);
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string commentId)
        {
            string returnUrl = Request.Headers["Referer"].ToString();

            var accessToken = await HttpContext.GetTokenAsync("access_token");           

            await _baseService.Delete(commentId, RouteConst.CommentRoute, accessToken);

            return Redirect(returnUrl);
        }
    }
}

PasteBinClone/PasteBinClone.Web/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using PasteBinClone.Web.Interfaces;
using PasteBinClone.Web.Models;
using PasteBinClone.Web.Models.ViewModel;
using PasteBinClone.Web.Request;
using PasteBinClone.Web.Services;

namespace PasteBinClone.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LanguageController : Controller
    {
        private readonly IBaseService _baseService;
        private readonly IDistributedCache _cache;
        public LanguageController(IBaseService baseService, IDistributedCache cache)
        {
            _baseService = baseService;
            _cache = cache;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetAll(RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a list of Languages
                List<LanguageVM> languages = JsonConvert.DeserializeObject<List<LanguageVM>>(response.Data.ToString());

                return View(languages);
            }
            else
            {
                return NotFound();
            }
        }

        //Get - Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Post - Create
        [HttpPost]
        public async Task<IActionResult> Create(LanguageVM languageVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Post(languageVM, 
                RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
        //Get - Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetById(id, 
                RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a Language
                LanguageVM language = JsonConvert.DeserializeObject<LanguageVM>(response.Data.ToString());

                return View(language);
            }
            else
            {
                return NotFound();
            }
        }

        //Post - Edit
        [HttpPost]
        public async Task<IActionResult> Edit(LanguageVM languageVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Put(languageVM, 
                RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        //Get - Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetById(id, 
                RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a Language
                LanguageVM language = JsonConvert.DeserializeObject<LanguageVM>(response.Data.ToString());

                return View(language);
            }
            else
            {
                return NotFound();
            }
        }

        //Post - Delete
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Delete(id, 
                RouteConst.LanguageRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                _cache.Remove("filters");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

PasteBinClone/PasteBinClone.Web/Controllers/TypeController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using PasteBinClone.Web.Interfaces;
using PasteBinClone.Web.Models;
using PasteBinClone.Web.Models.ViewModel;
using PasteBinClone.Web.Request;
using System.Collections.Generic;

namespace PasteBinClone.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TypeController : Controller
    {
        private readonly IBaseService _baseService;
        private readonly IDistributedCache _cache;

        public TypeController(IBaseService baseService, IDistributedCache cache)
        {
            _baseService = baseService;
            _cache = cache;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetAll(RouteConst.TypeRoute, accessToken);

            if(response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a list of ContentTypes
                List<ContentTypeVM> contentTypes = JsonConvert.DeserializeObject<List<ContentTypeVM>>(response.Data.ToString());

                return View(contentTypes);
            }
            else
            {
                return NotFound();
            }

        }

        //Get - Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Post - Create
        [HttpPost]
        public async Task<IActionResult> Create(ContentTypeVM typeVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Post(typeVM, 
                RouteConst.TypeRoute, accessToken);

            if(response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        //Get - Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetById(id, 
                RouteConst.TypeRoute, accessToken);

            if(response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a ContentType
                ContentTypeVM contentType = JsonConvert.DeserializeObject<ContentTypeVM>(response.Data.ToString());

                return View(contentType);
            }
            else
            {
                return NotFound();
            }
        }

        //Post - Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Delete(id, 
                RouteConst.TypeRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                _cache.Remove("filters");
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }


        //Get - Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.GetById(id, 
                RouteConst.TypeRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                //Deserialization of the received object into a ContentType
                ContentTypeVM contentType = JsonConvert.DeserializeObject<ContentTypeVM>(response.Data.ToString());

                return View(contentType);
            }
            else
            {
                return NotFound();
            }
        }

        //Post - Edit
        [HttpPost]
        public async Task<IActionResult> Edit(ContentTypeVM typeVM)
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var response = await _baseService.Put(typeVM, 
                RouteConst.TypeRoute, accessToken);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

PasteBinClone/PasteBinClone.Web/Views/Shared/_CommentForm.cshtml
@model CommentVM

<form asp-controller="Comment" asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" name="PasteId" value="@Model.PasteId" />

    <div>
        <div class="mb-2">
            <div>
                <label class="form-label filter-text ms-2">Add Comments</label>
            </div>
            <div>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <textarea class="form-control" rows="3" asp-for="Body"></textarea>
        </div>
        <div class="text-end">
            <button class="btn comment-btn btn-outline-secondary roboto-regular" type="submit">Add Comment</button>
        </div>
    </div>
</form>

PasteBinClone/PasteBinClone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PasteBinClone.Web</title>
    <link href="https://fonts.googleapis.com/css2?family=Inria+Serif&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=K2D:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;1,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PasteBinClone.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-background">
            <div class="container-fluid d-flex justify-content-md-center">

                <a class="navbar-brand navbar-brand-text-style text-decoration-none text-dark" asp-controller="Home" asp-action="Index">PasteBin</a>

                <div class="position-absolute top-50 end-0 translate-middle-y me-3">
                    <div class="navbar-nav ms-auto">
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="navbar__button-admin nav-item dropdown">
                                <a class="nav-link dropdown-toggle" style="color:#7D7D7D;" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin menu
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Type" asp-action="Index">Type</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a></li>
                                </ul>
                            </div>
                        } 
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="Profile" asp-action="Index" class="user-name text-decoration-none text-dark">@User.Identity.Name</a>
                            <a class="btn btn-outline-secondary navbar__button navbar__button-signup" asp-action="Logout" asp-controller="Home">LOG OUT</a>
                        }
                        else
                        {
                            <a class="btn navbar__button navbar__button-login" asp-action="Login" asp-controller="Home">LOG IN</a>
                            <a class="btn btn-outline-secondary navbar__button navbar__button-signup" asp-action="Signup" asp-controller="Home">SIGN UP</a>
                        }
                    </div>
                </div>

            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PasteBinClone.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/cc9056737c.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PasteBinClone/PasteBinClone.Web/Views/Shared/_RatingForm.cshtml
@model RatingVM

<form method="post" asp-controller="Rating" asp-action="Create">

    <div class="row mb-5 mt-1">

        <input type="hidden" name="PasteId" value="@Model.PasteId" />

        <div class="col-auto row ms-2 d-flex align-items-center">
            <span class="col roboto-regular p-2 text-center">@Model.Likes</span>

            @if (Model.CurrentIsLiked)
            {
                <button class="btn btn-secondary col ms-2 like-btn p-2" type="submit" name="IsLiked" value="true">
                    <i class="fa-regular fa-thumbs-up"></i>
                </button>
            }
            else
            {
                <button class="btn col ms-2 like-btn btn-outline-secondary p-2" type="submit" name="IsLiked" value="true">
                    <i class="fa-regular fa-thumbs-up"></i>
                </button>
            }
        </div>

        <div class="col-auto row ms-2 d-flex align-items-center">
            <span class="col roboto-regular p-2 text-center">@Model.Dislikes</span>

            @if (Model.CurrentIsDisliked)
            {
                <button class="btn btn-secondary col ms-2 dislike-btn p-2" type="submit" name="IsDisliked" value="true">
                    <i class="fa-regular fa-thumbs-down"></i>
                </button>
            }
            else
            {
                <button class="btn col ms-2 dislike-btn btn-outline-secondary p-2" type="submit" name="IsDisliked" value="true">
                    <i class="fa-regular fa-thumbs-down"></i>
                </button>
            }
        </div>
    </div>

</form>